### ISSUE TITLE
Привязка к сессии, чтобы вариативные значения реже повторялись

### ISSUE THREAD

**Issue by vitalets** [vitalets/alice-renderer#1]
Сейчас значения из массивов выбираются случайно. Это приводит к тому, что значения повторяются несколько раз подряд для одного пользователя. Это делает ответы более "роботными". Например:
```js
const successWord = ['Отлично', 'Супер', 'Зд+орово'];

const success = () => reply`${successWord}! Это правильный ответ!`;

// может оказаться так:
// => "Супер! Это правильный ответ!"
// => "Супер! Это правильный ответ!"
// => "Супер! Это правильный ответ!"
```
Было бы круто привязать ответы к сессии пользователя, чтобы гарантированно исключать повторения. Примерно так:
```js
const successWord = ['Отлично', 'Супер', 'Зд+орово'];

const success = ctx => ctx.reply`${successWord}! Это правильный ответ!`;

// => "Супер! Это правильный ответ!"
// => "Отлично! Это правильный ответ!"
// => "Зд+орово! Это правильный ответ!"
```
Над синтаксисом надо еще  подумать.

**Comment by mecurc** [comment]
Возможно я что-то не понимаю, но разве взаимодейтствие с сессией это задача этой библиотеки?

Сессия это некий контекст, реализация и работа с которым может быть очень разной.

**Comment by vitalets** [comment]
> Возможно я что-то не понимаю, но разве взаимодейтствие с сессией это задача этой библиотеки?

По хорошему конечно это не ее задача. Она должна чисто рендерингом ответов заниматься и все. Но проблема с повторами есть, и хочется для нее придумать решение удобное.

**Comment by vitalets** [comment]
Поразмышлял на выходных, концепт такой.
Заводим функцию `userify`, которая позволяет обернуть функции рендеринга под конкретный id пользователя. Например:
```js
const {reply, userify} = require('alice-renderer');

const successWords = ['Отлично', 'Супер', 'Зд+орово'];
const success = () => reply`${successWords}! Это правильный ответ!`;

ctx.success = userify(session.user_id, success);

const response = ctx.success();

// => "Супер! Это правильный ответ!"
// => "Отлично! Это правильный ответ!"
// => "Зд+орово! Это правильный ответ!"
```

Также можно передать объект, тогда обернуться все его методы:
```js
// replies.js
exports.welcome = () => ...
exports.success = () => ...
exports.bye = () => ...

// logic.js
const replies = require('./replies');

ctx.replies = userify(session.user_id, replies);

const response = ctx.replies.welcome();
...
```
Под капотом userify проксирует вызовы к исходному объекту, передавая рандомайзеру уже выпавшие варианты для конкретного user_id. Если выпали все варианты, то начинаем сначала.
Главное требование - функции рендеринга обязаны быть синхронными. Что должно быть всегда правдой при хорошей архитектуре.

**Comment by vitalets** [comment]
Released in [0.3.0](https://github.com/vitalets/alice-renderer/releases/tag/v0.3.0).
