### ISSUE TITLE
Использовать es2015 imports

### ISSUE THREAD

**Issue by mecurc** [vitalets/alice-renderer#2]
Я хочу использовать эту библиотеку на cloudflare-workers. Под капотом там v8-isolates и браузерное окружение.

Я использую rollup для сборки проекта и чтобы использовать этот пакет я вынужден тащить `rollup-plugin-commonjs` и `rollup-plugin-node-resolve`.

Если использовать esmodules, то иблитека станет более универсальной, а это приятно :)

**Comment by vitalets** [comment]
Интересная штука эти cloudflare-workers, почитал про них - надо попробовать на них захоститься. Спасибо )

На счет переписывания в es imports - честно говоря не вижу большого смысла делать это сейчас. Все-таки основное окружение для библиотеки - node.js. Усложнять сборку не хочется. А стабильные es модули в ноду завезут только [в 2020 году](http://2ality.com/2018/12/nodejs-esm-phases.html#when-can-i-use-es-modules-on-nodejs).
В документации cloudflare подключение npm модулей показано через require. Так что мне кажется, использование этих плагинов - самый тру-вей )

Кстати а есть какой-то измеряемый минус их использования? Сборка сильно медленнее или что-то еще? Если я правильно понимаю, они же в рантайм воркеров не попадают?

**Comment by mecurc** [comment]
> Интересная штука эти cloudflare-workers, почитал про них - надо попробовать на них захоститься.

Они еще и поднимаются быстрее лямбд/cloud-functions, стоят дешевле и работают быстрее.

> А стабильные es модули в ноду завезут только в 2020 году.

Там это не единственная проблема. Они не очень совместимы с уже привычными нам ES modules, только внешне похожи.

> Кстати а есть какой-то измеряемый минус их использования? Сборка сильно медленнее или что-то еще? Если я правильно понимаю, они же в рантайм воркеров не попадают?

Несколько наносекунд к времени сборки. И иногда некорректно работают ( в случаях когда require вызвается в теле if или какой-либо функции). Проблемы с tree shaking.

**Comment by fletcherist** [comment]
Согласен, какие-то космические корабли эти клаудфларевские воркеры)
крутая тема, тоже теперь слежу

**Comment by vitalets** [comment]
> Согласен, какие-то космические корабли эти клаудфларевские воркеры)
> крутая тема, тоже теперь слежу

О да :) Веб-контекст, но на сервере %)

@mecurc Дима, а есть уже навык в продакшене на этих воркерах?
Мне интересно, как туда вкручиваются остальные классические библиотеки под ноду. 
Например, скрипт newrelic для монитоинга или клиент для монги.

**Comment by mecurc** [comment]
В основном я использовал воркеры для прослойки между апишками и простых авторизаций. В качестве базы данных я "тыкал" в  Google Firestore и Cloudflare KV.

https://developers.cloudflare.com/workers/writing-workers/storing-data/
https://github.com/GitbookIO/firebase-on-cloudflare

Возможно @xanf сможет подсказать, у него есть опыт перевода проекта с гугл-облака в воркеры и вроде-как удалось сильно снизить затраты денег в результате.

**Comment by vitalets** [comment]
Пока остаемся на `require`.
